# Generated by Django 5.2.5 on 2025-08-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('billing_cycle', models.CharField(default='monthly', max_length=20)),
                ('category', models.CharField(choices=[('web', 'Web Hosting'), ('wordpress', 'WordPress Hosting'), ('woocommerce', 'WooCommerce Hosting'), ('email', 'Email Hosting')], max_length=20)),
                ('features', models.TextField(help_text='List of features separated by semicolons')),
                ('is_popular', models.BooleanField(default=False)),
            ],
        ),
    ]
