# Generated by Django 5.2.5 on 2025-08-31 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0004_customerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('value', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(choices=[('text', 'Text'), ('check', 'Check'), ('times', 'Times')], default='text', max_length=8)),
                ('order', models.PositiveIntegerField(default=0, help_text='Sort order for this row')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='hosting.hostingplan')),
            ],
            options={
                'ordering': ['order', 'label', 'id'],
                'unique_together': {('plan', 'label')},
            },
        ),
    ]
