# Generated by Django 5.2.5 on 2025-08-10 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=160)),
                ('template_slug', models.SlugField(max_length=120)),
                ('is_published', models.BooleanField(default=False)),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('settings', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('path', models.CharField(default='/', max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.CharField(blank=True, default='', max_length=300)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='web_builder.project')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('key', models.CharField(choices=[('hero', 'Hero'), ('features', 'Features'), ('gallery', 'Gallery'), ('pricing', 'Pricing'), ('faq', 'FAQ'), ('cta', 'CTA')], max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('props', models.JSONField(blank=True, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='web_builder.page')),
            ],
            options={
                'ordering': ['position', 'id'],
                'unique_together': {('page', 'key', 'position')},
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'template_slug'], name='web_builder_user_id_ce1eae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('project', 'slug')},
        ),
    ]
