# Generated by Django 5.2.5 on 2025-08-10 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='blog_blogpo_status_aa5436_idx',
            old_name='blog_blogpo_status__b88a67_idx',
        ),
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='blog_blogpo_slug_361555_idx',
            old_name='blog_blogpo_slug_2b8fb6_idx',
        ),
    ]
